### ISSUE TITLE
parsing gRPC messages from Envoy TAP

### ISSUE THREAD

**Issue by salrashid123** [psanford/lencode#5]
thanks for this.

not sure i'm using this library in exactly the intended way but it looks to be useful to parse the type of raw gRPC messages from [Envoy TAP](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/tap_filter).

the messages there are raw and were prefixed with a `0` (which isn't really a prefix but the `compression-flag` per [gRPC over HTTP2](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)

```golang
dec := lencode.NewDecoder(buf, lencode.SeparatorOpt([]byte{0}))
````

here's the end-to-end sample 

https://github.com/salrashid123/envoy_tap#grpc

**Comment by psanford** [comment]
Yup, that's not the intended use of the separator, but hey, if it works :+1: . 

From those docs it looks like `PROTO_BINARY_LENGTH_DELIMITED` is defined as a varint. I wouldn't expect that to work for any messages bigger than 128 bits. I'd be open to supporting varints as an optional mode in this library if that would be useful.

BTW, your TPM related projects are very cool. https://github.com/salrashid123/aws_hmac was a very useful reference for me for https://github.com/psanford/awsv4signer.

**Comment by salrashid123** [comment]
ok,  i didn't check messages larger than that size.  I'll test it out; it was really done for academic reasons after somone in my team asked...if someone voices intereest in the parsing for large messages and support for it, i'll refer back here (i'll verify it too myself in a bit)

re: tpm, thanks; thats cool that its wrapped into a standalone, cleaner cli like that.
(i spent a lot of time on that type of stuff,...if interested in variation and generating JWT's alone, golang-jwt support
   * https://github.com/salrashid123/golang-jwt-tpm
   * https://github.com/salrashid123/golang-jwt-yubikey  (thats as of last night too)
